#!/bin/bash

BASEDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
EXECUTABLE="$(dirname "$BASEDIR")/bin/rshell"

echo "TEST COMMAND"
echo "------------------"
{
    echo "test -e bin"
    echo "test -f precedence_test.sh"
    echo "test -d bin"
    echo "test -d /bin"
    echo "test -e "
    echo "test"
    echo "test blah bin"
    echo "test -? bin"
    echo "test -de bin"
    echo "test -d -e bin"
    echo "test bin && ls"
    echo "test - bin && ls"
    echo "test bin || test -d src && ls"
    echo "test [ all.sh ]"
    echo "test  bin ;"
    echo "test ../tests ; [ -d ../src ; ]"
    echo "pwd ;test -d bin && ls -a;	#exit"
    echo "	(test -f bin || echo 1) && ( ech || [ -d bin ] && ls)"
    echo "(test -d src || pwd ) &&([ bin ] || echo 1)" 
    echo "test -e bin || ([ -f ../src || pwd ])"
    echo "test -e bin || ([ -f bin ] || pwd )"
    echo "test -e bin || ([ -f bin || pwd )"
    echo "test -d ../tests && ([ -f bin || pwd )"
    echo "exit"
} | $EXECUTABLE $1
